version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./ventas_contables.db
      - SECRET_KEY=change-this-in-production
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/ventas_contables.db:/app/ventas_contables.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
