name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Railway
        run: echo "Railway auto-deploys from GitHub"

      - name: Deploy to Vercel
        run: echo "Vercel auto-deploys from GitHub"
